spring:
  application:
    name: finfintech

  datasource:
    url: jdbc:mysql://localhost:3306/finfintech?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  jwt:
    secret: ZmluZmludGVjaC1zcHJpbmctYm9vdCBwcm9qZWN0

