spring:
  application:
    name: finfintech
  redis:
    host: localhost
    port: 6379
  datasource:
      url: jdbc:mysql://localhost:3306/finfintech?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  jwt:
    secret: ZmluZmludGVjaC1zcHJpbmctYm9vdCBwcm9qZWN0
